dataset:
  class: datasets.MNISTDataset

model:
  name: ConvNetExample
  class: mnist_convnet.SimpleConvNet

  optimizer:
    class: AdamOptimizer
    learning_rate: 0.001

  inputs: [images, labels]
  outputs: [accuracy, predictions, loss]

main_loop:
  extra_streams: [test]

hooks:
  - ComputeStats:
      variables: [loss, accuracy]
  - LogVariables
  - CatchSigint
  - StopAfter:
      minutes: 2
